# Generated by Django 5.2.1 on 2025-05-17 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seats.seat', verbose_name='預約座位'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', '已預約'), ('cancelled', '已取消')], default='reserved', max_length=10, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='預約使用者'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='座位編號'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='x',
            field=models.IntegerField(default=0, verbose_name='X 座標'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Y 座標'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(blank=True, null=True, verbose_name='發生日期')),
                ('reported_time', models.TimeField(blank=True, null=True, verbose_name='發生時間')),
                ('reason', models.TextField(verbose_name='檢舉原因')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('resolved', '已處理'), ('dismissed', '已駁回')], default='pending', max_length=10, verbose_name='處理狀態')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='管理員備註')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='檢舉人')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.seat', verbose_name='被檢舉座位')),
            ],
            options={
                'verbose_name': '檢舉',
                'verbose_name_plural': '檢舉',
            },
        ),
    ]
