# Generated by Django 5.2.1 on 2025-05-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0003_report_reported_user_alter_report_reporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-submitted_at'], 'verbose_name': '檢舉', 'verbose_name_plural': '檢舉'},
        ),
        migrations.AddField(
            model_name='report',
            name='reported_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.reservation', verbose_name='被檢舉的預約'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('resolved', '已處理'), ('dismissed', '已駁回'), ('confirmed', '已確認')], default='pending', max_length=10, verbose_name='處理狀態'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', '已預約'), ('cancelled', '已取消'), ('completed', '已完成')], default='reserved', max_length=10, verbose_name='狀態'),
        ),
    ]
